on:
  release:
    types: [created]
  workflow_dispatch:

name: Rustun Release Linux
jobs:
  rustun:
    strategy:
      matrix:
        include:
          - build: linux
            os: linux-latest
            rust: stable
            runson: ubuntu-latest
            target: x86_64-unknown-linux-musl
            arch: x86_64
            cross: false
          - build: linux_arm64
            os: linux-latest
            runson: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-musl
            arch: aarch64
            cross: false
    runs-on: ${{ matrix.runson }}
    steps:
      - uses: actions/checkout@v4
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Add rust Target
        run: |
          rustup target add ${{ matrix.target }}
          rustup target list
      - name: Build rustun
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --all-features --target ${{ matrix.target }}
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/${{ matrix.target }}/release/.fingerprint
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/${{ matrix.target }}/release/examples
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/${{ matrix.target }}/release/build
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/${{ matrix.target }}/release/incremental
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/${{ matrix.target }}/release/examples
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: target/${{ matrix.target }}/release/deps
      - name: Remove Files
        run: |
          rm -rf target/${{ matrix.target }}/release/*.d
          rm  -rf target/${{ matrix.target }}/release/*.rlib
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "tar"
          filename: ../../../rustun.${{ matrix.os }}.${{ matrix.arch }}.tar.gz
          directory: target/${{ matrix.target }}/release
          path: .
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: rustun.${{ matrix.os }}.${{ matrix.arch }}.tar.gz
          asset_name: rustun.${{ matrix.os }}.${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip
